<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FKH366F" failures="0" tests="6" name="com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality" time="1.075" errors="2" timestamp="07 May 2018 17:12:47 GMT" skipped="3">
  <testcase classname="com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality" name="CloseObjects" time="0.001">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.orion.qa.base.OrionBase.CloseBrowser(OrionBase.java:178)
	at com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality.CloseObjects(Test_NewTimeSheet_SubmitFunctionality.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:212)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- CloseObjects -->
  <testcase classname="com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality" name="Test_LoginToOrion_IsSuccess" time="0.055"/>
  <testcase classname="com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality" name="Test_IfNewTimeSheetPage_Isdisplayed" time="1.019">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.orion.qa.pages.TimeSheetEditPage.lbl_TimeSheet(TimeSheetEditPage.java:20)
	at com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality.Test_IfNewTimeSheetPage_Isdisplayed(Test_NewTimeSheet_SubmitFunctionality.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Test_IfNewTimeSheetPage_Isdisplayed -->
  <testcase classname="com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality" name="Test_IfSubmitMessage_IsDisplayed" time="0.000">
    <skipped/>
  </testcase> <!-- Test_IfSubmitMessage_IsDisplayed -->
  <testcase classname="com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality" name="Test_IfDataSubmittedCorrectly" time="0.000">
    <skipped/>
  </testcase> <!-- Test_IfDataSubmittedCorrectly -->
  <testcase classname="com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality" name="Test_LogoutfromOrion_IsSuccess" time="0.000">
    <skipped/>
  </testcase> <!-- Test_LogoutfromOrion_IsSuccess -->
</testsuite> <!-- com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality -->
