<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FKH366F" failures="1" tests="5" name="com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality" time="2.192" errors="0" timestamp="02 May 2018 14:30:30 GMT" skipped="3">
  <testcase classname="com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality" name="Test_LoginToOrion_IsSuccess" time="0.905"/>
  <testcase classname="com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality" name="Test_IfNewTimeSheetPage_Isdisplayed" time="1.287">
    <failure message="expected [TimeSheet New Time Sheet] but found [Time Sheet]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [TimeSheet New Time Sheet] but found [Time Sheet]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality.Test_IfNewTimeSheetPage_Isdisplayed(Test_NewTimeSheet_SubmitFunctionality.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test_IfNewTimeSheetPage_Isdisplayed -->
  <testcase classname="com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality" name="Test_IfSubmitMessage_IsDisplayed" time="0.000">
    <skipped/>
  </testcase> <!-- Test_IfSubmitMessage_IsDisplayed -->
  <testcase classname="com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality" name="Test_IfDataSubmittedCorrectly" time="0.000">
    <skipped/>
  </testcase> <!-- Test_IfDataSubmittedCorrectly -->
  <testcase classname="com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality" name="Test_LogoutfromOrion_IsSuccess" time="0.000">
    <skipped/>
  </testcase> <!-- Test_LogoutfromOrion_IsSuccess -->
</testsuite> <!-- com.orion.qa.testcases.Test_NewTimeSheet_SubmitFunctionality -->
